### PR TITLE
Fix a shadow warning in thrust's execute_with_dependencies.h

### LINKED ISSUE #335: [BUG]: Shadow warning in thrust
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

Thrust

### Describe the bug

Using cuda12, I observe a shadow warning in thrust.

The relevant code is here:
https://github.com/NVIDIA/thrust/blob/24486a169a62a58ef8f824d3dc9613c006b6f5a7/thrust/detail/execute_with_dependencies.h#L60-L64

Line 60 is shadowed by line 64. I guess a simple renaming would help.

### How to Reproduce

Compile thrust with all warnings enabled.

### Expected behavior

No warnings of course

### Reproduction link

_No response_

### Operating System

Alma8

### nvidia-smi output

_No response_

### NVCC version

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

### PR DESCRIPTION
**Pull request by hageboeck**
[skip-tests]

Fix https://github.com/NVIDIA/thrust/issues/1980
Fix #335 

Moved to here from https://github.com/NVIDIA/thrust/pull/1981#issuecomment-1678908015

## Checklist

- [?] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by miscco — APPROVED** [review]

**Comment by miscco** [comment]
Thanks a lot for the contribution 🎉

**Comment by hageboeck** [comment]
Now the issue is also in this repo:
#335

**Comment by miscco** [comment]
@jarmak-nv Shouldnt this PR get someone assigned?

**Review by jrhemstad — APPROVED** [review]

**Comment by miscco** [comment]
@wmaxey I believe we do not want this also backported to 2.2 It is only a warning after all?

**Comment by miscco** [comment]
Thanks a lot for the contribution 🎉

**Pull request merged**
