### PR TITLE
Rename thrust example `version.cu` to `print_version.cu`

### PR DESCRIPTION
**Pull request by j3soon**
If we follow the README to compile `version.cu` into an `version` executable, this will cause compilation of some other source files to fail:

    In file included from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/cuda/std/detail/libcxx/include/version:214,
                     from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/cuda/std/version:26,
                     from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/cuda/std/detail/libcxx/include/cstddef:50,
                     from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/cuda/std/cstddef:26,
                     from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/thrust/detail/config/cpp_compatibility.h:31,
                     from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/thrust/detail/config/config.h:37,
                     from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/thrust/detail/config.h:22,
                     from /opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/thrust/binary_search.h:23,
                     from weld_vertices.cu:1:
    ./version:11:121: error: extended character |  is not valid in an identifier

The following line in `/opt/nvidia/hpc_sdk/Linux_x86_64/24.11/cuda/12.6/include/cuda/std/detail/libcxx/include/version:214`:

    #  include <version>

mistakenly identified the `version` executable as the file to include. This issue can be resolved by renaming the file, as done in this commit.

Tested with docker image: `nvcr.io/nvidia/nvhpc:24.11-devel-cuda_multi-ubuntu22.04`.

### CODE REVIEW

**Comment by j3soon** [comment]
Hi, I'm also surprised too. The following are the minimal steps to reproduce this issue:

```sh
docker run --rm -it --gpus all nvcr.io/nvidia/nvhpc:24.11-devel-cuda_multi-ubuntu22.04
# in the container
cd ~
git clone --depth 1 -b v2.5.0 https://github.com/NVIDIA/cccl.git
cd ~/cccl/thrust/examples
nvcc -o version version.cu
nvcc -o weld_vertices weld_vertices.cu
# observe the error
```

**Comment by bernhardmgruber** [comment]
I see. It seems you are not using CMake, the preferred way to setup and build CCCL. We also offer devcontainers, which offer a really nice integration with VSCode. You can find more information here: https://github.com/NVIDIA/cccl/blob/main/.devcontainer/README.md

The error you describe is expected then, because you mix binary and source directories. That is, your compiled executables are put in the same directory as source files (`~/cccl/thrust/examples`). So when you run `nvcc`, which eventually includes `<version>` it will look in the local directory first and try to wrongly include the binary. This does not happen if you put the binaries in a dedicated build directory, as is common practice with CMake.

**Comment by j3soon** [comment]
Thanks for the information on devcontainers!

Currently, I'm using CCCL pre-installed in the `nvhpc` container to compile some example code. I found that the [`thrust/examples`](https://github.com/NVIDIA/cccl/blob/main/thrust/examples) directory isn't designed to run `cmake` without re-building thrust/cccl, which will result in the following error:

```
root@f45840095039:~/cccl/thrust/examples# cmake .
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/CMakeLists.txt:1 (thrust_update_system_found_flags):
  Unknown CMake command "thrust_update_system_found_flags".
```

Therefore, I simply follow the thrust examples README to build them in the same directory with `nvcc`: https://github.com/NVIDIA/cccl/blob/main/thrust/examples/README.md

A similar fix would be modifying `thrust/examples/CMakeLists.txt` to support running `cmake` directly in the examples folder. However, I'm unsure if I can make those changes without breaking things.

**Comment by bernhardmgruber** [comment]
> Currently, I'm using CCCL pre-installed in the `nvhpc` container to compile some example code. I found that the [`thrust/examples`](https://github.com/NVIDIA/cccl/blob/main/thrust/examples) directory isn't designed to run `cmake` without re-building thrust/cccl

Ah, yes. I guess we only ship the examples but not all the CMake stuff around it. So I guess it would be better to experiment with a git clone of this repository.

> Therefore, I simply follow the thrust examples README to build them in the same directory with `nvcc`: https://github.com/NVIDIA/cccl/blob/main/thrust/examples/README.md

Makes sense. I will add some more information here to prefer playing with the public git repo, because it contains better infrastructure.

> A similar fix would be modifying `thrust/examples/CMakeLists.txt` to support running `cmake` directly in the examples folder. However, I'm unsure if I can make those changes without breaking things.

@alliepiper what do you think? Should the `CMakeLists.txt` for Thrust examples be standalone, so CMake can be used to build examples shipped as part of a CTK?

**Comment by bernhardmgruber** [comment]
> I will add some more information here to prefer playing with the public git repo, because it contains better infrastructure.

PR up: #3004

**Comment by bernhardmgruber** [comment]
Thank you for the contribution!

**Pull request merged**
