### PR TITLE
simplify the code that marks cccl headers as system headers

### PR DESCRIPTION
**Pull request by ericniebler**
## Description

if this passes CI it will be a simplification of the code used in all cccl headers to mark them as "system" headers. i tried older versions of nvcc on godbolt and this _seems_ to work. let's see what CI says.

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by jrhemstad** [comment]
@miscco can correct me if I'm wrong, but I think I recall it was nvc++ that broke and kept us from doing it as a single line before?

**Comment by ericniebler** [comment]
eh, it's not worth it. closing.

**Comment by miscco** [comment]
Yeah it is breaking ICC and nvc++

**Comment by bernhardmgruber** [comment]
Is this an existing problem with nvc++? If not, what is the last version that had this problem? I would love to see this changeset land eventually.

ICC is already deprecated and will be removed at some point.

**Pull request closed without merging**
