### PR TITLE
`constexpr` all the things

### PR DESCRIPTION
**Pull request by pb-dseifert**
## Description
Make the `CUB` codebase `constexpr` consistent.

### CODE REVIEW

**Comment by pb-dseifert** [comment]
@jrhemstad cleaned up the formatting

**Review by miscco — APPROVED** [review]

**Review by elstehle — APPROVED** [review]

**Comment by miscco** [comment]
Thanks a lot for the contribution 🎉 

I am sure Jason will be proud 😸

**Pull request merged**
