### PR TITLE
[libcu++] Add _LIBCUDACXX_CUDACC_BELOW_12_3 macro

### PR DESCRIPTION
**Pull request by gonzalobg**
Adds a new macro to detect CTKs < 12.3.

### CODE REVIEW

**Review by miscco — APPROVED** [review]
Is there a reason you split this out of the other PR?

**Comment by gonzalobg** [comment]
I couldn't add this with an inline suggestion.

**Review by wmaxey — APPROVED** [review]

**Comment by wmaxey** [comment]
I'll merge this once CI is green.

**Pull request merged**
