### PR TITLE
make the upper limit on TMP loop unrolling configurable

### PR DESCRIPTION
**Pull request by ericniebler**
## Description

@bernhardmgruber has discovered that the CUDA front end is spending an inordinate amount of time processing `__type_list.h`. it's possible that this is caused by excessive use of the preprocessor to unroll template recursion. this PR makes the unroll limit configurable so we can easily test that hypothesis.

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
Taking your PR as is and compiling:
```c++
#include <cuda/std/__type_traits/type_list.h>
int main() {}
```
I see this trace:
image
`type_list.h` takes 498ms to parse.

**Comment by bernhardmgruber** [comment]
Trying `_CCCL_META_UNROLL_LIMIT` from 1 to 16:
```
for i in $(seq 1 16); do echo -n "$i: "; time nvcc -fdevice-time-trace trace --extended-lambda -D_CCCL_META_UNROLL_LIMIT=$i -Icccl/cub -Icccl/thrust -Icccl/libcudacxx/include -c ./tl.cu -o tl.o; done

1:1.248
2:1.249
3:1.249
4:1.250
5:1.249
6:1.243
7:1.251
8:1.254
9:1.260
10:1.276
11:1.281
12:1.307
13:1.369
14:1.497
15:1.742
16:2.223
```
Everything until 8 looks good.

The benchmark is probably not great, because this regards only header parsing time.

**Comment by bernhardmgruber** [comment]
This is `type_list.pass.cpp`:
`nvcc -fdevice-time-trace trace -Icccl/libcudacxx/include -x cu ./type_list.pass.cpp`
image
It's interesting to see that parsing the header takes a lot longer than template instantiation.

**Comment by bernhardmgruber** [comment]
Different unrollings for `type_list.pass.cpp`:
```
$ for i in $(seq 1 16); do echo -n "$i:"; time nvcc -D_CCCL_META_UNROLL_LIMIT=$i -Icccl/libcudacxx/include -x cu -c ./type_list.pass.cpp -o tl.o; done
1:1.999
2:1.969
3:1.961
4:1.963
5:1.941
6:1.961
7:1.976
8:2.010
9:2.015
10:2.008
11:2.021
12:2.141
13:2.185
14:2.341
15:2.669
16:3.287
```

**Review by miscco — APPROVED** [review]

**Comment by miscco** [comment]
looks like 10 is the sweet spot

**Comment by ericniebler** [comment]
I suspect the sweet spot is different for different compilers.

**Review by miscco — APPROVED** [review]

**Pull request merged**
