### PR TITLE
Fix: make launchers a CUB detail; make kernel source functions hidden.

### LINKED ISSUE #3207: [BUG] CUB launchers should be a detail, but aren't

### LINKED ISSUE #3208: [BUG] CUB kernel source member functions should be hidden symbols, as they return kernel pointers

### PR DESCRIPTION
**Pull request by griwes**
## Description

This is a cleanup PR that resolves a couple of issues introduced with #2448.

First, the new launcher factory and launcher APIs are not currently for public consumption, but they were not placed into detail directories/namespaces. This is now fixed.

Second, the new concept of a kernel source, which abstracts the process of instantiating CUB kernels from the dispatch layers, does not correctly hide its member functions that return kernel pointers; this would result in issues in the case of programs linking together two copies of CUB, compiled with their own separate runtimes, where the runtime linker would select one of the versions of those functions, breaking the users of the other one. This should now be fixed. I went for `_CCCL_HIDE_FROM_ABI`, as that seems to me to be the most robust option that we currently have for this kind of thing, but if there's concerns about this specific solution, please let me know.

Resolves #3207
Resolves #3208 

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by gevtushenko** [comment]
pre-commit.ci autofix

**Review by gevtushenko — COMMENTED** [review]
I think `_CCCL_HIDE_FROM_ABI` is missing on:
1. `TripleChevronFactory::MaxSmOccupancy`
2. `CudaDriverLauncher::doit`
3. `CudaDriverLauncherFactory::MaxSmOccupancy`

**Comment by griwes** [comment]
@gevtushenko went a little wider than what you listed with the additional HIDE_FROM_ABIs, please sanity check.

**Review by gevtushenko — APPROVED** [review]

**Pull request merged**
