### PR TITLE
Rebase 2.4.x with main.

### PR DESCRIPTION
**Pull request by wmaxey**
## Description

Wraps several fixes from main into 2.4.x including the patch PR.

### CODE REVIEW

**Review by miscco — APPROVED** [review]

**Review by jrhemstad — APPROVED** [review]

**Review by jrhemstad — APPROVED** [review]

**Review by miscco — CHANGES_REQUESTED** [review]
Are we sure that this is the right appraoach. AFAIK this would create one gigantic merge commit.

Shouldnt we just reset the branch to the current main?

**Comment by wmaxey** [comment]
> Are we sure that this is the right appraoach. AFAIK this would create one gigantic merge commit.
> 
> Shouldnt we just reset the branch to the current main?

This will be fine, we just don't squash. I'll do a FF once the CI is calm and we stop adding commits. :)

**Review by miscco — APPROVED** [review]

**Review by jrhemstad — APPROVED** [review]

**Pull request merged**
