### PR TITLE
Fix flakey heterogeneous tests

### LINKED ISSUE #2031: Fix failing nightly jobs
There is a PR that enables the failing jobs in CI (using the `override` workflow in `ci/matrix.yaml`). This can be used to fix them before we re-enable the nightly jobs.

https://github.com/NVIDIA/cccl/pull/1847

### PR DESCRIPTION
**Pull request by wmaxey**
Concurrent H/D writes can fail when testing barrier or latch. A solution is to remove concurrent write access from tests. Multiple threads can concurrently write, however only the CPU or GPU should be doing any writing. I've restructured the tests such that they are still thematically testing in the same way, but fence write access to only one component at a time.

For example, semaphore tests now fence acquire and release so that write access to the shared value only occurs from one processor at a time. An example execution sequence might look like:

```
Acquire 3 (CPU)
Fence
Release 3 (GPU)
Fence
Acquire 3 (CPU)
```

## Description

partially closes #2031

## Checklist

- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Review by miscco — APPROVED** [review]

**Comment by wmaxey** [comment]
pre-commit.ci autofix

**Review by griwes — APPROVED** [review]

**Review by miscco — APPROVED** [review]

**Pull request merged**
