### PR TITLE
Increase the libcu++ timeout

### PR DESCRIPTION
**Pull request by miscco**
We are frequently running into  to the current test duration limit of 01:20, so add another 20 minutes to the timeout.

### CODE REVIEW

**Comment by miscco** [comment]
See e.g https://github.com/NVIDIA/cccl/actions/runs/10936067428/job/30370307989?pr=2376

Note that with 2271 tests that is still less than 2.5s per test, so I believe we are fine

**Comment by jrhemstad** [comment]
Somewhere along the way we seemed to have lost running lit with the `--time-tests` option that would show the top 10 longest tests. Can we add that back in this PR so we can make sure there isn't some test taking an exorbitant amount of time?

**Comment by alliepiper** [comment]
FYI: Merging in main to use new, smaller PR matrix.

**Comment by jrhemstad** [comment]
image
bitset tests are a little sus, but not extreme enough to warrant blocking this PR.

**Review by jrhemstad — APPROVED** [review]

**Pull request merged**
