### PR TITLE
backport `forward_like`

### PR DESCRIPTION
**Pull request by davebayer**
This PR introduces trivial backport of C++23 `forward_like` to C++11.

### CODE REVIEW

**Comment by davebayer** [comment]
pre-commit.ci autofix

**Review by miscco — COMMENTED** [review]
Could you update the standard api section in the docs

**Review by miscco — APPROVED** [review]

**Comment by davebayer** [comment]
pre-commit.ci autofix

**Review by miscco — APPROVED** [review]

**Pull request merged**
