### PR TITLE
Match_any testing single bit by fusing into single LOP3 instruction

### PR DESCRIPTION
**Pull request by IlyaGrebnov**
I also observed that implementation of the match_any function could also be optimized a bit. Presently, it employs "setp.eq.u32 p, %0, %2;" instead of "setp.ne.u32 p, %0, 0;". While functionally this is equivalent when testing a single bit, adopting != 0 could enable a fusion of the 'and' and 'testp' operations into a single LOP3 instruction in area where ALU intensity is high.

## Description

closes 

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by IlyaGrebnov** [comment]
Adding @gevtushenko. Related to #1353.

**Comment by gevtushenko** [comment]
Hello @IlyaGrebnov and thank you for the contribution! The change is functionally sound. Regarding the performance, the modified matcher is used in both one-sweep and legacy implementations of radix sort. I haven't noticed any performance implications of the modification for legacy implementation on Ada. On Hopper, I verified the one-sweep radix sort and noticed the following improvements (`cub.bench.radix_sort.key.base`):

|  T{ct}  |  OffsetT{ct}  |  Elements{io}  |  Entropy  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |         Diff |   %Diff | 
|---------|---------------|----------------|-----------|------------|-------------|------------|-------------|--------------|---------|
|   I8    |      I32      |      2^28      |     1     |   2.012 ms |       0.17% |   1.891 ms |       0.20% |  -121.101 us |  -6.02% |
|   I8    |      I32      |      2^28      |   0.544   |   2.047 ms |       0.19% |   1.927 ms |       0.17% |  -120.168 us |  -5.87% |
|   I8    |      I32      |      2^28      |   0.201   |   1.931 ms |       0.23% |   1.819 ms |       0.19% |  -112.443 us |  -5.82% |
|   I8    |      I64      |      2^28      |     1     |   2.015 ms |       0.22% |   1.871 ms |       0.15% |  -144.243 us |  -7.16% |
|   I8    |      I64      |      2^28      |   0.544   |   2.048 ms |       0.17% |   1.910 ms |       0.12% |  -138.827 us |  -6.78% |
|   I8    |      I64      |      2^28      |   0.201   |   1.931 ms |       0.25% |   1.804 ms |       0.18% |  -127.396 us |  -6.60% |
|   I16   |      I32      |      2^28      |     1     |   4.023 ms |       2.86% |   3.644 ms |       0.08% |  -378.705 us |  -9.41% |
|   I16   |      I32      |      2^28      |   0.544   |   4.209 ms |       1.42% |   3.720 ms |       0.07% |  -488.886 us | -11.62% |
|   I16   |      I32      |      2^28      |   0.201   |   4.063 ms |       2.13% |   3.501 ms |       0.11% |  -562.381 us | -13.84% |
|   I16   |      I64      |      2^28      |     1     |   4.558 ms |       1.98% |   3.827 ms |       2.83% |  -731.257 us | -16.04% |
|   I16   |      I64      |      2^28      |   0.544   |   4.595 ms |       1.51% |   3.942 ms |       2.40% |  -653.133 us | -14.21% |
|   I16   |      I64      |      2^28      |   0.201   |   4.392 ms |       1.64% |   3.743 ms |       3.34% |  -649.402 us | -14.79% |
|   I32   |      I32      |      2^28      |     1     |  10.090 ms |       3.23% |   8.644 ms |       3.15% | -1446.080 us | -14.33% |
|   I32   |      I32      |      2^28      |   0.544   |  10.055 ms |       1.22% |   8.937 ms |       2.37% | -1117.937 us | -11.12% |
|   I32   |      I32      |      2^28      |   0.201   |   9.430 ms |       1.43% |   8.553 ms |       1.98% |  -877.821 us |  -9.31% |
|   I32   |      I64      |      2^28      |     1     |  11.337 ms |       3.00% |  10.753 ms |       2.76% |  -583.636 us |  -5.15% |
|   I32   |      I64      |      2^28      |   0.544   |  10.697 ms |       1.70% |  10.189 ms |       1.90% |  -507.839 us |  -4.75% |
|   I32   |      I64      |      2^28      |   0.201   |   9.924 ms |       0.94% |   9.458 ms |       2.33% |  -466.480 us |  -4.70% |
|   I64   |      I32      |      2^28      |     1     |  33.310 ms |       4.28% |  33.381 ms |       3.70% |    71.307 us |   0.21% |
|   I64   |      I32      |      2^28      |   0.544   |  29.281 ms |       1.28% |  29.050 ms |       2.40% |  -230.515 us |  -0.79% |
|   I64   |      I32      |      2^28      |   0.201   |  27.416 ms |       1.37% |  26.790 ms |       1.04% |  -626.124 us |  -2.28% |
|   I64   |      I64      |      2^28      |     1     |  35.035 ms |       3.37% |  35.853 ms |       3.40% |   818.781 us |   2.34% |
|   I64   |      I64      |      2^28      |   0.544   |  29.487 ms |       2.14% |  30.133 ms |       3.27% |   646.062 us |   2.19% |
|   I64   |      I64      |      2^28      |   0.201   |  27.171 ms |       0.98% |  26.836 ms |       2.02% |  -335.135 us |  -1.23% |
|  I128   |      I32      |      2^28      |     1     | 110.171 ms |       7.28% | 112.164 ms |       3.00% |     1.993 ms |   1.81% |
|  I128   |      I32      |      2^28      |   0.544   |  96.061 ms |       0.65% |  98.031 ms |       0.28% |     1.970 ms |   2.05% |
|  I128   |      I32      |      2^28      |   0.201   |  92.361 ms |       0.72% |  92.941 ms |       1.04% |   580.883 us |   0.63% |
|  I128   |      I64      |      2^28      |     1     | 108.963 ms |       0.40% | 113.142 ms |       4.27% |     4.179 ms |   3.84% |
|  I128   |      I64      |      2^28      |   0.544   |  95.998 ms |       0.70% |  97.608 ms |       0.23% |     1.610 ms |   1.68% |
|  I128   |      I64      |      2^28      |   0.201   |  92.155 ms |       0.20% |  93.472 ms |       0.23% |     1.317 ms |   1.43% |
|   F32   |      I32      |      2^28      |     1     |  13.050 ms |       3.19% |  13.143 ms |       3.11% |    93.252 us |   0.71% |
|   F32   |      I32      |      2^28      |   0.544   |  11.477 ms |       1.74% |  11.882 ms |       0.37% |   405.233 us |   3.53% |
|   F32   |      I32      |      2^28      |   0.201   |  10.983 ms |       1.73% |  11.348 ms |       0.44% |   365.063 us |   3.32% |
|   F32   |      I64      |      2^28      |     1     |  12.755 ms |       2.84% |  12.732 ms |       2.17% |   -22.981 us |  -0.18% |
|   F32   |      I64      |      2^28      |   0.544   |  11.846 ms |       2.30% |  11.798 ms |       1.76% |   -48.464 us |  -0.41% |
|   F32   |      I64      |      2^28      |   0.201   |  11.185 ms |       0.82% |  11.023 ms |       2.33% |  -162.295 us |  -1.45% |
|   F64   |      I32      |      2^28      |     1     |  35.449 ms |       1.90% |  36.697 ms |       4.50% |     1.248 ms |   3.52% |
|   F64   |      I32      |      2^28      |   0.544   |  31.617 ms |       1.61% |  31.508 ms |       3.66% |  -109.100 us |  -0.35% |
|   F64   |      I32      |      2^28      |   0.201   |  29.512 ms |       1.38% |  29.553 ms |       2.40% |    40.671 us |   0.14% |
|   F64   |      I64      |      2^28      |     1     |  36.028 ms |       4.57% |  37.312 ms |       4.91% |     1.284 ms |   3.56% |
|   F64   |      I64      |      2^28      |   0.544   |  31.565 ms |       1.69% |  32.129 ms |       2.31% |   563.540 us |   1.79% |
|   F64   |      I64      |      2^28      |   0.201   |  29.880 ms |       1.92% |  29.955 ms |       2.17% |    75.507 us |   0.25% |

Random regressions for larger types are within the noise threshold. There's visible improvement for smaller types. 

While I'm verifying performance in other use cases, I wanted to double-check if you are interested in device-scope optimization or have the block scope in mind? If you are interested in block scope, is there any chance you could share a benchmark you've used to verify this change?

**Comment by IlyaGrebnov** [comment]
@gevtushenko 

I do not have a specific benchmark to measure the performance of radix sort since I discovered this issue while working on a similar problem of computing LF-mapping for Burrows-Wheeler-Transform (used for data compression in bzip2 and my libbsc). This algorithm is essentially a single round of OneSweep sorting U8 keys, but instead of scattering the keys, the output is the ranks (positions where the keys should be scattered). Code is [here](https://github.com/IlyaGrebnov/libcubwt/blob/d8b7f80be7c75659d61fa0465135b88b482bcde7/libcubwt.cu#L2520).

While I was memory bound, I still noticed stalls which prompted me to investigate further. This investigation first led me to the realization that __math_any_sync is not a native SASS institution and is likely emulated and is sensitive to input. Additionally, the CUB variant also showed some stalls which led to further inspection at the instruction level.

That being said, I do not think this is actually a CUB issue. I believe the driver should be smarter and capable of generating a single LOP3 instruction in this case. Essentially, the comparison ((A & B) == B) could be treated as ((A & B) != 0) if B is a constant and has only one bit set.

**Comment by IlyaGrebnov** [comment]
@gevtushenko sorry for pinging on the PR and it looks like we are still waiting for more sign-off, but is anything need from my side?

**Comment by gevtushenko** [comment]
> @gevtushenko sorry for pinging on the PR and it looks like we are still waiting for more sign-off, but is anything need from my side?

@IlyaGrebnov sorry for the delay. The PR is good to go as soon as CI is green.

**Review by gevtushenko — APPROVED** [review]

**Pull request merged**
