### PR TITLE
Drop thrusts diagnostic suppression warnings

### PR DESCRIPTION
**Pull request by miscco**
We have global suppression warnings for CCCL, so use them

This is helpful for #2386

### CODE REVIEW

**Comment by miscco** [comment]
@gevtushenko this might be a tad controversial, but I am of the opinion that the thrust warning suppression macros should be considered as implementation details and not user facing.

A user can always silence warnings on their own

**Review by bernhardmgruber — COMMENTED** [review]
I love the refactoring, but removing the macros is technically a breaking change :S

**Comment by miscco** [comment]
> I love the refactoring, but removing the macros is technically a breaking change :S

It technically is but iin my opinion warning suppression is an implementation detail that should have never been public and I am willing break that

**Review by bernhardmgruber — APPROVED** [review]

**Review by gevtushenko — APPROVED** [review]
> @gevtushenko this might be a tad controversial, but I am of the opinion that the thrust warning suppression macros should be considered as implementation details and not user facing.

I agree, these macro should've been an implementation detail. If we were to keep them part of public API, we'd have to add compilation tests and documentation.

**Pull request merged**
