### PR TITLE
Fix code sample in README and docs

### LINKED ISSUE #1651: [BUG]: Sample Code in CUB README and docs does not compile
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

CUB

### Describe the bug

The code was taken from `cub/examples/block/example_block_radix_sort.cu` but slightly modified. The modified version is missing `cub::` in two locations for it to compile.

Bug [found](https://stackoverflow.com/q/78352524/10107454) by [Zhixiong Xiao](https://stackoverflow.com/users/17496320/zhixiong-xiao) on StackOverflow.com

### How to Reproduce

1. Take code from CUB's README.md
2. Try to compile it.

### Expected behavior

It should compile without errors.

### Reproduction link

https://cuda.godbolt.org/z/o7ba9f388

### Operating System

_No response_

### nvidia-smi output

_No response_

### NVCC version

_No response_

### PR DESCRIPTION
**Pull request by pauleonix**
Add missing namespace specifiers that were overlooked when https://github.com/NVIDIA/cccl/blob/29a24f49c26640e8d9e250ec20797698a6a92027/cub/examples/block/example_block_radix_sort.cu#L50 was removed.

## Description

closes #1651

## Checklist

- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Review by miscco — APPROVED** [review]

**Comment by pauleonix** [comment]
Sorry, found out that the same applies to index.rst as well.

**Comment by pauleonix** [comment]
Fixed another problem in `index.rst` (see the linked issue).

**Pull request merged**
