### PR TITLE
Fix Thrust/CUB tests by adding empty base opt-ins to iterator classes

### PR DESCRIPTION
**Pull request by wmaxey**
## Description

closes nvbug/4911089 && nvbug/4920716 && further challenges my sanity

By using `-Xcompiler /d1reportSingleClassLayout__tuple_impl` on NVCC we can see that the tuple base has a different class size when it contains Thrust iterators. I've written a test that outputs the difference when compiled with MSVC vs NVCC.

```
#ifdef __CUDACC__
__global__ void test() {
  {
    thrust::counting_iterator<uint64_t> begin(0);
    thrust::counting_iterator<uint64_t> end(5);
    auto zip = thrust::make_zip_iterator(begin, end);
    printf("%llu\n", sizeof(zip));
  }

  {
    auto zip = cuda::std::make_tuple((uint64_t)0ll, (uint64_t)5ll);
    printf("%llu\n", sizeof(zip));
  }
}
#endif
int main() {
  {
    thrust::counting_iterator<uint64_t> begin(0);
    thrust::counting_iterator<uint64_t> end(5);
    auto zip = thrust::make_zip_iterator(begin, end);
    printf("%llu\n", sizeof(zip));
  }

  {
    auto zip = cuda::std::make_tuple((uint64_t)0ll, (uint64_t)5ll);
    printf("%llu\n", sizeof(zip));
  }

#ifdef __CUDACC__
  test<<<1,1>>>();
  cudaDeviceSynchronize();
#endif
}
```

On NVCC this outputs:
```
24
16
16
16
```

MSVC (Only after applying the missing ebo declspec to the forward declaration of `__tuple_impl` though):
```
16
16
```

Thrust's classes needed to be changed as well. I expect this is *some kind of NVCC bug* as the declspec shouldn't need to be bubbled up to iterator interfaces.

## Checklist

- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by wmaxey** [comment]
pre-commit.ci autofix

**Review by miscco — APPROVED** [review]

**Comment by bernhardmgruber** [comment]
Could we add a test to CCCL that detects this in the future?

**Pull request merged**
