### PR TITLE
Propagate compiler flags down to libcu++ LIT tests

### LINKED ISSUE #2415: [BUG]: libcu++ tests fail with clang builds because compiler flags are not propagated to lit tests.
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

In order to run libcu++ tests with clang lit has to use correct compiler settings.
It currently appears to rely on clang automatically finding and using
the default CUDA installation, but that's not necessarily the CUDA that
the build itself may have been configured to use.

Clang builds may also require building them with the host libc++, instead of the default libstdc++.
That requires propagation of the top-level CFLAGS specified by the user.

The end result, is that when I attempted to run libcu++ tests locally, with CUDA installed under `/usr/local/cuda-12.3.1`.
`--cuda-path` was never propagated to LIT, and that caused a lot of secondary failures as all compiler invocations were failing, including those lit used to figure out which options/features were available.

### How to Reproduce

- Checkout cccl:branch/v2.6.x
- PATH=$HOME/local/cuda-12.3.1/bin:$PATH CUDAFLAGS="--cuda-path=$HOME/local/cuda-12.3.1 -stdlib=libc++ -D_ALLOW_UNSUPPORTED_LIBCPP" CXXFLAGS="-stdlib=libc++" "./ci/build_libcudacxx.sh" -std "20" -cuda /home/tra/work/llvm/build/release/bin/clang++ -cxx /home/tra/work/llvm/build/release/bin/clang++ -arch 80-real
- these flags are sufficient to build the libcu++ itself, but the tests fail early in the lit configuration stage.

```
[1779/1780] cd /usr/local/google/home/tra/work/cuda/cccl/build/libcudacxx-cpp20/libcudacxx/test/libcudacxx && /usr/bin/cmake -E env LIBCUDACXX_SITE_CONFIG=/usr/local/google/home/tra/work/cuda/cccl/build/libcudacxx-cpp20/libcudacxx/test/libcudacxx/lit.site.cfg /usr/local/google/home/tra/.local/bin/lit -vv --no-progress-bar -Dexecutor="NoopExecutor()" /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/libcudacxx
FAILED: libcudacxx/test/libcudacxx/CMakeFiles/libcudacxx.test.lit.precompile /usr/local/google/home/tra/work/cuda/cccl/build/libcudacxx-cpp20/libcudacxx/test/libcudacxx/CMakeFiles/libcudacxx.test.lit.precompile
cd /usr/local/google/home/tra/work/cuda/cccl/build/libcudacxx-cpp20/libcudacxx/test/libcudacxx && /usr/bin/cmake -E env LIBCUDACXX_SITE_CONFIG=/usr/local/google/home/tra/work/cuda/cccl/build/libcudacxx-cpp20/libcudacxx/test/libcudacxx/lit.site.cfg /usr/local/google/home/tra/.local/bin/lit -vv --no-progress-bar -Dexecutor="NoopExecutor()" /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/libcudacxx
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py:41: note: using site specific configuration at /usr/local/google/home/tra/work/cuda/cccl/build/libcudacxx-cpp20/libcudacxx/test/libcudacxx/lit.site.cfg
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/libcudacxx/lit.cfg:45: note: Using configuration variant: libcudacxx
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py:245: note: Using executor: 'NoopExecutor()'
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py:444: note: inferred use_system_cxx_lib as: None
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py:330: note: detected cxx.type as: clang
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py:332: note: detected cxx.version as: ('20', '0', '0')
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py:334: note: detected cxx.default_dialect as: c++17
lit: /usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py:473: note: inferred use_clang_verify as: False
lit: /usr/local/google/home/tra/.local/share/pipx/venvs/lit/lib/python3.11/site-packages/lit/TestingConfig.py:152: fatal: unable to parse config file '/usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/libcudacxx/lit.cfg', traceback: Traceback (most recent call last):
  File "/usr/local/google/home/tra/.local/share/pipx/venvs/lit/lib/python3.11/site-packages/lit/TestingConfig.py", line 140, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/libcudacxx/lit.cfg", line 52, in <module>
    configuration.configure()
  File "/usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py", line 194, in configure
    self.configure_compile_flags()
  File "/usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py", line 639, in configure_compile_flags
    self.configure_default_compile_flags()
  File "/usr/local/google/home/tra/work/cuda/cccl/libcudacxx/test/utils/libcudacxx/test/config.py", line 788, in configure_default_compile_flags
    raise OSError("Configured compiler does not support flag {0}".format(stdflag))
OSError: Configured compiler does not support flag -std=c++20

ninja: build stopped: subcommand failed.

```

Lit misleadingly reports failure to parse config file, but the underlying reason is that the compiler invocation failed because it could not find the CUDA SDK.

### Expected behavior

CCCL build should propagate top-level compiler options down to the LIT tests as the test compilation should be done with the same CUDA and host standard library versions.

### Reproduction link

_No response_

### Operating System

Custom debian distribution.

### nvidia-smi output

n/a

### NVCC version

```
bin/clang++ --version
clang version 20.0.0git
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/tra/work/llvm/build/release/bin
Build config: +assertions
```

### PR DESCRIPTION
**Pull request by Artem-B**
closes #2415  

In order to run libcu++ tests with clang lit has to use correct compiler settings. It currently appears to rely on clang automatically finding and using the default CUDA installation, but that's not necessarily the CUDA that the build itself may have been configured to use.

Clang builds may also require building them with the host libc++, instead of the default libstdc++. That requires propagation of the top-level CFLAGS specified by the user.

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by fbusato** [comment]
sorry @Artem-B, what is the relation with #2419 ?

**Comment by Artem-B** [comment]
> sorry @Artem-B, what is the relation with #2419 ?

Sorry, made a typo. It's #2415

**Comment by Artem-B** [comment]
Thank you for cleaning it up and merging it.

**Pull request merged**
