### PR TITLE
Add script to update RAPIDS version.

### PR DESCRIPTION
**Pull request by bdice**
## Description

This PR adds an update script to manage RAPIDS and devcontainer updates. It also applies the script, updating the versions to 24.10. The update script can be invoked like this: `ci/update_rapids_version.sh 24.10.00`

Supersedes #2079:

> @miscco fixed some compilation errors caused by removing long-time deprecated CUB facilities in: https://github.com/rapidsai/cudf/pull/16377. However, this fixes were targeted to the 24.10 branch, while our CI keeps building the 24.08 branch.
>
> This PR changes our CI jobs to build against with the 24.10 branch.

## Checklist
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
The rapidsai jobs are failing now with:
```
Unknown CUDA [12.5] compiler [rapids-conda] combination
Requested devcontainer .devcontainer/cuda12.5-rapids-conda/devcontainer.json does not exist
```

**Comment by bdice** [comment]
Interesting -- there was a symlink that needed renaming. I tried to fix this from the GitHub web interface in f34d020 but it messed up the filename. Now it shows as `cuda12.5-rapids-conda -> '../ci/rapids/cuda12.5-conda'$'\n'` on my machine. I'll fix again from the terminal.

**Review by bernhardmgruber — COMMENTED** [review]
LGTM for everything except the `update_rapids_version.sh` for which I lack the expertise in shell scripting and knowledge whether this conflicts with any of our workflows (e.g. How does this relate to `make_devcontainers.sh`)

Can anybody else review the shell script please? Maybe @alliepiper? Thx!

The CI errors are unrelated.

**Comment by bdice** [comment]
@bernhardmgruber For reference, the update script is modified from a very similar script used for updating RAPIDS repositories. Here is cuDF’s corresponding script: https://github.com/rapidsai/cudf/blob/branch-24.10/ci/release/update-version.sh

I envision this script being used 1-2 weeks after each new RAPIDS release is opened for development, which is roughly now for the 24.10 release. The short delay allows for any unrelated issues to be ironed out and devcontainers to be created.

The script is set to modify both the matrix from which devcontainers are generated AND the devcontainer configs themselves. This means it should leave the devcontainers in a consistent state with the matrix.

**Review by miscco — APPROVED** [review]

**Pull request merged**
