### PR TITLE
Remove remaining C++03 compatibility from unit tests

### PR DESCRIPTION
**Pull request by Blonck**
As part of #127, code for unsupported compilation modes/platforms will be removed. This patch removes all remaining checks against C++03 which were left after #378.

This patch relates to #127 and #378.

## Checklist
- [x] I am familiar with the [Contributing Guidelines]

### CODE REVIEW

**Comment by Blonck** [comment]
@miscco this are the remaining C++03 unit test left over from #378.

**Comment by Blonck** [comment]
You addressed all comments from your review in your commit, or? So nothing left to do?

**Comment by miscco** [comment]
Only addressing the merge conflics I just introduces :)

**Review by miscco — APPROVED** [review]

**Pull request merged**
