### PR TITLE
Apply clang-format to cub

### PR DESCRIPTION
**Pull request by bdice**
## Description

This applies clang-format to CUB. With #1588 and the pre-commit.ci bot, autoformatting can be applied to any PR by commenting `pre-commit.ci autofix`.

All changes were automatically applied aside from the edits to `.pre-commit-config.yaml`.

See also:
- https://github.com/NVIDIA/cccl/issues/455
- https://github.com/NVIDIA/cccl/issues/456
- https://github.com/NVIDIA/cccl/issues/1589

## Checklist
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by alliepiper** [comment]
> Do we want to break this down and apply it in chunks somehow?

This might be a necessity, the changes view is crashing my browser 😄

Maybe 1 PR per project?

**Comment by wmaxey** [comment]
I'm under the impression we're going to want to exclude libcudacxx at least temporarily. We need to prevent clang-format from touching `nv/target` and probably figure out if we need a different format for the rest of the headers.

**Comment by jrhemstad** [comment]
> I'm under the impression we're going to want to exclude libcudacxx at least temporarily. We need to prevent clang-format from touching `nv/target` and probably figure out if we need a different format for the rest of the headers.

We agreed in https://github.com/NVIDIA/cccl/pull/551 to just have a single `.clang-format` for everything. I understand omitting `nv/target`, but everything else should be fair game.

**Comment by wmaxey** [comment]
.

> > I'm under the impression we're going to want to exclude libcudacxx at least temporarily. We need to prevent clang-format from touching `nv/target` and probably figure out if we need a different format for the rest of the headers.
> 
> We agreed in #551 to just have a single `.clang-format` for everything. I understand omitting `nv/target`, but everything else should be fair game.

I'm happy with that. I looked at the changes and the surgery done isn't too impactful. `<nv/target>` was excluded already for some reason.

**Comment by bdice** [comment]
@jrhemstad @wmaxey @alliepiper I'm a little unsure of the conclusion to draw from the discussion above. Should I make a change and apply clang-format to the entire repo? Or break up the formatting into one PR per subproject as @alliepiper proposed?

**Comment by miscco** [comment]
I believe we should drop any additional `.clang-format` files.

`<nv/target>` can be dealt with a `// clang-format off` comment at the beginning of the file and `// clang-format on` at the end

It will be a trainwreck in our libcu++ test suite as we often have terribly long lines there, but I am absolutely in favor of just getting something in over the current state

**Comment by miscco** [comment]
I saw some issues with the formatting in libcu++ though.

It was not properly aligning consecutive alias definitions

**Comment by alliepiper** [comment]
> I'm a little unsure of the conclusion to draw from the discussion above. Should I make a change and apply clang-format to the entire repo?

Making a separate PR for each repo will simplify reviewing and let us discuss and deal with each one's issues separately, since some will probably be easier to land than others.

**Comment by alliepiper** [comment]
While we're at it, we should probably add something like this to track these big formatting sweeps: https://github.com/NVIDIA/nvbench/blob/main/.git-blame-ignore-revs

**Comment by bdice** [comment]
.git-blame-ignore-revs is a good idea, but it will have to be done in follow-up PRs because the commit hashes will not be known in advance due to squash merging.

**Review by miscco — APPROVED** [review]

**Review by miscco — APPROVED** [review]

**Review by gevtushenko — APPROVED** [review]
@bdice thank you for this effort! Setting up an auto-formatting was long overdue for CUB. I had a few minor fixes that I pushed to your branch.

**Comment by bdice** [comment]
@gevtushenko Awesome, thanks! Please merge when you’re ready. @miscco volunteered to do the follow-ups for enabling clang-format on Thrust and libcudacxx.

**Comment by miscco** [comment]
Thanks a lot for working on this @bdice its awesome 🎉

**Pull request merged**
