### PR TITLE
Add support for sm_101 and sm_101a to NV_TARGET

### PR DESCRIPTION
**Pull request by bernhardmgruber**

### CODE REVIEW

**Review by miscco — APPROVED** [review]

**Review by wmaxey — APPROVED** [review]

**Comment by johnnynunez** [comment]
@bernhardmgruber 
10.0 blackwell b100/b200
10.1 blackwell thor
10.1a blackwell digits
12.0 blackwell rtx50

**Comment by jrhemstad** [comment]
@johnnynunez can you tell us more about what questions you have?

**Comment by johnnynunez** [comment]
> @johnnynunez can you tell us more about what questions you have?

I know that:
10.0 blackwell b100/b200
10.1 blackwell thor
12.0 blackwell rtx50

But exists sm_100a and 101a
Is arm laptops and digits?
I’m putting support in frameworks when new cuda 12.7 and 12.8 will be published

**Comment by johnnynunez** [comment]
image

**Pull request merged**
