### PR TITLE
Forward declare half types in `cuda::ptx`

### LINKED ISSUE #2933: [BUG]: cuda::ptx takes long to compile
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Performance

### Component

libcu++

### Describe the bug

Including `<cuda/ptx>` takes ~800ms on my workstation.

### How to Reproduce

Comparing the time to compile an empty file, a file including `cuda/ptx` and a file including `cuda/std/__type_traits/integral_constant.h` (which is included from `cuda/ptx`). 
```
$ echo "" > empty.cu
$ echo "#include <cuda/ptx>" > cuda_ptx.cu
$ echo "#include <cuda/std/__type_traits/integral_constant.h>" > cuda_std_integral_constant.cu
$ hyperfine --warmup 1 'nvcc -arch sm_90a -x cu -c empty.cu -o test.o'  'nvcc -arch sm_90a -x cu -c cuda_ptx.cu -o test.o'  'nvcc -arch sm_90a -x cu -c cuda_std_integral_constant.cu -o test.o'

Benchmark 1: nvcc -arch sm_90a -x cu -c empty.cu -o test.o
  Time (mean ± σ):      1.434 s ±  0.012 s    [User: 1.070 s, System: 0.368 s]
  Range (min … max):    1.414 s …  1.455 s    10 runs

Benchmark 2: nvcc -arch sm_90a -x cu -c cuda_ptx.cu -o test.o
  Time (mean ± σ):      2.299 s ±  0.022 s    [User: 1.861 s, System: 0.442 s]
  Range (min … max):    2.275 s …  2.339 s    10 runs

Benchmark 3: nvcc -arch sm_90a -x cu -c cuda_std_integral_constant.cu -o test.o
  Time (mean ± σ):      2.131 s ±  0.023 s    [User: 1.709 s, System: 0.426 s]
  Range (min … max):    2.098 s …  2.167 s    10 runs
```

### Expected behavior

This should not be a heavy header.

### Reproduction link

_No response_

### Operating System

Ubuntu Linux 22.04

### nvidia-smi output

NA

### NVCC version

Benchmark was performed using prerelease version of nvcc, but should be reproducible with any recent version.

### PR DESCRIPTION
**Pull request by ahendriksen**
## Description

closes #2933

Forward declare half types to avoid including the (expensive) fp16 headers.

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
That's great work! Compiling:
```
#include <cuda/ptx>
int main() {}
```
with
`nvcc -fdevice-time-trace trace -Icccl/cub -Icccl/thrust -Icccl/libcudacxx/include ./ptx.cu`

now shows this trace:
image

`ptx.h` takes 12ms to compile. Great work!

**Review by bernhardmgruber — APPROVED** [review]

**Comment by miscco** [comment]
I am not a fan of this, because it might break existing code that looks whether those names are available. We should guard those with the macros and only replace the include with the forward declaration

**Comment by bernhardmgruber** [comment]
Can you elaborate what you mean with "those names"? Are you referring to whether the types `__half` and `__nv_bfloat16` are visible and could be used in SFINAE?

So we should guard the forward declaratiions by `_LIBCUDACXX_HAS_NVFP16` etc.?

**Comment by miscco** [comment]
Yes unconditionally forward declaring names might break code. We should guard that with the feature macros

**Pull request merged**
