### PR TITLE
clean up complex.inl

### PR DESCRIPTION
**Pull request by ZelboK**
while trying to understand thrusts `complex` i noticed a bunch of useless outdated macros that can be removed

### CODE REVIEW

**Comment by miscco** [comment]
pre-commit.ci autofix

**Comment by miscco** [comment]
I would advice to not spend too much time with `thrust::complex` The only reason it is still there are numerical issues in our `cuda::std::complex` implementation. It will be gone soon ^TM

**Review by bernhardmgruber — APPROVED** [review]

**Comment by bernhardmgruber** [comment]
@ZelboK Could you please rebase your PR on `main` and resolve the conflict? Thx!

**Comment by ZelboK** [comment]
cc @bernhardmgruber @jrhemstad

**Review by bernhardmgruber — APPROVED** [review]

**Comment by alliepiper** [comment]
pre-commit.ci autofix

**Comment by bernhardmgruber** [comment]
Thank you for your contribution!

**Pull request merged**
