### PR TITLE
Experimental Python cooperative algorithms

### PR DESCRIPTION
**Pull request by gevtushenko**
## Description

This PR adds Python library with speed-of-light cooperative block and warp level reduction, prefix sum, merge and radix sort.The API is in experimental stage, so there should be no concern with API stability for now. New sphinx project is intentionally omitted in the top-level toctree for now. 

Below is the performance comparison of segmented prefix sum implemented with block scan (prefix callback overload) in C++ and Python:

Screenshot 2024-07-10 at 5 33 04 PM

## Checklist

- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by gevtushenko** [comment]
pre-commit.ci autofix

**Review by jrhemstad — APPROVED** [review]

**Pull request merged**
